repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
    -   id: seed-isort-config
        args: [--exclude=cement/cli/templates]
        name: Identify known third party Python imports
-   repo: https://github.com/asottile/yesqa
    rev: v0.0.11
    hooks:
    -   id: yesqa
        name: Remove noqa annotations without specific codes
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
        name: Remove trailing whitespace
    -   id: fix-encoding-pragma
        args: [--remove]
        name: Remove unwanted Python encoding pragma
    -   id: end-of-file-fixer
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      name: Set Black code style to Python files
      language_version: python3.6
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.5.0-1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.10b0]
        name: Set Black code style to reStructuredText and Markdown files
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: pretty-format-json
        args: [--autofix]
        name: Set pretty formatting for JSON files
    -   id: mixed-line-ending
        args: [--fix=lf]
        name: Set UNIX line ending
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.26.2
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
        name: Set syntax for newer Python versions
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: file-contents-sorter
        files: docs/spelling_wordlist.txt
        name: Sort specified file contents
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-merge-conflict
        name: Check files for merge conflicts
    -   id: check-byte-order-marker
        name: Check files for unwanted byte-order marker
    -   id: check-symlinks
        name: Check for broken symlinks
    -   id: check-case-conflict
        name: Check for case conflicts in file names
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.4
    hooks:
    -   id: python-no-log-warn
        name: Check for deprecated Python logger method warn()
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-builtin-literals
        name: Check for literal syntax when initialising Python built-in types
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.4
    hooks:
    -   id: python-check-mock-methods
        name: Check for not real mock methods
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: debug-statements
        name: Check for Python debug statements
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.4
    hooks:
    -   id: python-use-type-annotations
        name: Check for Python type comments (use type annotations)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-added-large-files
        args: [--maxkb=500]
        name: Check for unwanted large files
    -   id: detect-private-key
        name: Check for unwanted private keys
    -   id: check-json
        name: Check JSON files are parseable
    -   id: check-vcs-permalinks
        name: Check links to VCS websites are permalinks
    -   id: check-executables-have-shebangs
        name: Check non-binary executables have shebangs
    -   id: flake8
        args: [--config=setup.cfg]
        additional_dependencies: [flake8-bugbear, flake8-mypy, pep8-naming]
        name: Check Python code style for conformance (Flake8)
    -   id: check-docstring-first
        name: Check Python docstrings appear before code
-   repo: https://github.com/chewse/pre-commit-mirrors-pydocstyle
    rev: v2.1.1
    hooks:
    -   id: pydocstyle
        files: pypackage/* tests/*
        name: Check Python docstrings for compliance (pydocstyle)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-ast
        name: Check Python files are parseable
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        name: Check Python import sort order (isort)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: name-tests-test
        args: [--django]
        files: tests/*
        name: Check test file names match test_*.py
    -   id: check-xml
        name: Check XML files are parseable
    -   id: check-yaml
        name: Check YAML files are parseable
